# Default values for nfs-server chart
image:
  registry: docker.io
  repository: sharedvolume/nfs-server-controller
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
              - arm64
          - key: kubernetes.io/os
            operator: In
            values:
              - linux

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

metrics:
  enabled: true
  port: 8080
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 30s
    scrapeTimeout: 10s

healthProbe:
  port: 8081

leaderElection:
  enabled: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s

# NFS Server Image configuration for the controller
nfsServerImage:
  # If set, this will be passed as NFS_SERVER_IMAGE environment variable
  # to the controller. If not set, the controller will use its default image.
  # Example: "sharedvolume/nfs-server:0.0.3-alpine-3.22.0"
  tag: ""
