# Default values for nfs-server.
# This is a YAML-formatted file.

replicaCount: 1

image:
  registry: docker.io
  repository: sharedvolume/nfs-server-controller
  tag: "latest"
  pullPolicy: IfNotPresent

global:
  imagePullSecrets: []
  kubernetesClusterDomain: cluster.local

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
              - amd64
              - arm64
          - key: kubernetes.io/os
            operator: In
            values:
              - linux

leaderElection:
  enabled: true

healthProbe:
  port: 8081

metrics:
  enabled: true
  port: 8080

# NFS Server Image configuration for pods managed by this controller
nfsServerImage: ""
