{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "shared-volume.nfsServer.labels" . | nindent 4 }}
  name: {{ include "shared-volume.nfsServer.serviceAccountName" . }}
  namespace: {{ .Values.nfsServer.namespace }}
  {{- with .Values.nfsServer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
