{{- if and .Values.sharedVolume.enabled .Values.sharedVolume.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shared-volume.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-volume.labels" . | nindent 4 }}
  {{- with .Values.sharedVolume.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
