# This is a placeholder deployment for the local nfs-server chart
# The actual controller deployment is handled by the main shared-volume chart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfs-server.fullname" . }}-placeholder
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  replicas: 0  # This is just a placeholder
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: placeholder
        image: busybox:1.28
        command: ['sh', '-c', 'echo "placeholder" && sleep 1']
