{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-server.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: http-metrics
  selector:
    {{- include "nfs-server.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
